### ISSUE TITLE
[Feature] Parse all configurable strings via MiniPlaceholders

### ISSUE THREAD

**Issue by unilock** [Jarva/VelocityCarbonDiscord#3]
It would be nice to have all strings available in the configuration parsed through MiniPlaceholders, to allow for much more customization than just the placeholders made available by VelocityCarbonDiscord. (I noticed this was not already the case when attempting to use [`<server_name>`](https://github.com/MiniPlaceholders/MiniPlaceholders/wiki/Placeholders#server-expansion) in #2.)

At the very least, I think it would make sense for the following strings to be parsed through MiniPlaceholders:
```yaml
discord:
   messages:
      chat_message: '<username>: <message>'
      join_message: '**<username> joined <server>**'
      leave_message: '**<username> left <server>**'
      disconnect_message: '**<username> was disconnected**'
      server_switch_message: '**<username> moved from <previous_server> to <server>**'
   webhook:
      username: '<username>'
      message: '<message>'
```
