### ISSUE TITLE
[Feature] List available placeholders for every string in config

### ISSUE THREAD

**Issue by unilock** [Jarva/VelocityCarbonDiscord#4]
It would be helpful to know what placeholders are provided by VelocityCarbonDiscord for *every* string in the configuration. For example:

```yaml
discord:
   token: 'TOKEN'
   messages:
      # Available placeholders: <username> <message>
      chat_message: '<username>: <message>'
      # Available placeholders: <username> <server>
      join_message: '**<username> joined <server>**'
      # Available placeholders: <username> <server>
      leave_message: '**<username> left <server>**'
      # Available placeholders: <username>
      disconnect_message: '**<username> was disconnected**'
      # Available placeholders: <username> <server> <previous_server>
      server_switch_message: '**<username> moved from <previous_server> to <server>**'
etc.
```

(the above example may be more verbose than necessary)
